Vagrant.configure("2") do |config|

    # VM development environment
    config.vm.define "development" do |development|
        development.vm.box = "peru/ubuntu-18.04-desktop-amd64"
        development.vm.box_version = "20190901.01"
        development.vm.hostname = "development"
        development.vm.network :private_network, ip: "192.168.33.27"
        development.vm.synced_folder ".", "/vagrant"

        development.vm.provider "virtualbox" do |vb|
            vb.name = "development-environment"
            vb.memory = 2048
            vb.cpus = 2
        end
        development.vm.provision "shell", inline: <<-SHELL
            echo "nameserver 8.8.8.8" | sudo tee /etc/resolv.conf > /dev/null
            sudo apt-get update -y
            sudo apt-get install -y curl
            SHELL
        if Vagrant::Util::Platform.windows?
            development.vm.provision :guest_ansible do |ansible|
                ansible.verbose = "vvv"
                ansible.playbook = "ansible/target-environments-playbook.yml"
            end
        else
            development.vm.provision :ansible do |ansible|
                ansible.verbose = "vvv"
                ansible.playbook = "ansible/target-environments-playbook.yml"
            end
        end
    end

    # VM production environment
    config.vm.define "production" do |production|
        production.vm.box = "peru/ubuntu-18.04-desktop-amd64"
        production.vm.box_version = "20190901.01"
        production.vm.hostname = "production"
        production.vm.network :private_network, ip: "192.168.33.28"
        production.vm.synced_folder ".", "/vagrant"

        production.vm.provider "virtualbox" do |vb|
            vb.name = "production-environment"
            vb.memory = 2048
            vb.cpus = 2
        end
        production.vm.provision "shell", inline: <<-SHELL
            echo "nameserver 8.8.8.8" | sudo tee /etc/resolv.conf > /dev/null
            sudo apt-get update -y
            sudo apt-get install -y curl
            SHELL
        if Vagrant::Util::Platform.windows?
            production.vm.provision :guest_ansible do |ansible|
                ansible.verbose = "vvv"
                ansible.playbook = "ansible/target-environments-playbook.yml"
            end
        else
            production.vm.provision :ansible do |ansible|
                ansible.verbose = "vvv"
                ansible.playbook = "ansible/target-environments-playbook.yml"
            end
        end
    end
end
