Vagrant.configure("2") do |config|

    # VM development environment
    config.vm.define "jenkins" do |jenkins|
        jenkins.vm.box = "peru/ubuntu-18.04-desktop-amd64"
        jenkins.vm.box_version = "20190901.01"
        jenkins.vm.hostname = "jenkins"
        jenkins.vm.network :private_network, ip: "192.168.33.29"
        jenkins.vm.synced_folder ".", "/vagrant"

        jenkins.vm.provider "virtualbox" do |vb|
            vb.name = "jenkins-vm"
            vb.memory = 2048
            vb.cpus = 2
        end
        jenkins.vm.provision "shell", inline: <<-SHELL
            echo "nameserver 8.8.8.8" | sudo tee /etc/resolv.conf > /dev/null
            sudo apt-get update -y
            sudo apt-get install -y curl
            curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
            SHELL
        if Vagrant::Util::Platform.windows?
            jenkins.vm.provision :guest_ansible do |ansible|
                ansible.verbose = "vvv"
                ansible.playbook = "ansible/jenkins-playbook.yml"
            end
        else
            jenkins.vm.provision :ansible do |ansible|
                ansible.verbose = "vvv"
                ansible.playbook = "ansible/jenkins-playbook.yml"
            end
        end
    end
end
