Vagrant.configure("2") do |config|



    # Jenkins & Monitoring VM
    config.vm.define "jenkinsMonitoring" do |jenkinsMonitoring|
        jenkinsMonitoring.vm.box = "peru/ubuntu-18.04-desktop-amd64"
        jenkinsMonitoring.vm.box_version = "20190901.01"
        jenkinsMonitoring.vm.hostname = "jenkinsMonitoring"
        jenkinsMonitoring.vm.network :private_network, ip: "192.168.33.29"
        jenkinsMonitoring.vm.synced_folder ".", "/vagrant", type: "nfs"
        jenkinsMonitoring.ssh.insert_key = false

        jenkinsMonitoring.vm.provider "virtualbox" do |vb|
            vb.name = "jenkins-monitoring-vm"
            vb.memory = 4098
            vb.cpus = 2
        end
        jenkinsMonitoring.vm.provision "shell", inline: <<-SHELL
            echo "nameserver 8.8.8.8" | sudo tee /etc/resolv.conf > /dev/null
            sudo apt-get update -y
            sudo apt-get install -y curl
            SHELL

        if Vagrant::Util::Platform.windows?
            jenkinsMonitoring.vm.provision :guest_ansible do |ansible|
                ansible.verbose = "vvv"
                ansible.playbook = "ansible/jenkins-monitoring-playbook.yml"
            end
        else
            jenkinsMonitoring.vm.provision :ansible do |ansible|
                ansible.verbose = "vvv"
                ansible.playbook = "ansible/jenkins-monitoring-playbook.yml"
            end
        end
    end

end
