pipeline {
    agent any
    stages {
        stage('Checkout') {
            steps {
                git branch: 'development', credentialsId: '627f4c3c-4def-41de-a6c3-7ba3e9621e13', url: 'https://github.com/marie230/DevOpsCrudApp'
            }
        }
        stage('Install') {
            steps {
                sh 'npm install'
            }
        }
        stage('TSlint') {
            steps {
                sh 'ng lint'
            }
        }
        stage('Test') {
            steps {
                sh 'ng test --watch=false --no-progress --browsers=ChromeHeadless'
            }
        }
    }
}
